version: "3.8"

services:
  blog:
    image: nginx:alpine
    container_name: chirpy_blog
    ports:
      - "9527:80"
    volumes:
      - ./_site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
