name: Build and Deploy Chirpy Blog

on:
  push:
    branches:
      - main # 只监听 main 分支的提交，触发此工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 在 GitHub 提供的 Ubuntu 虚拟环境中运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 拉取仓库代码到 runner 本地

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
        # 安装指定版本的 Ruby 环境，Jekyll 依赖 Ruby

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        # 安装 bundler 以及 Gemfile 中声明的所有依赖包

      - name: Build Chirpy static site
        run: JEKYLL_ENV=production bundle exec jekyll build
        # 运行 Jekyll 构建静态站点，生成 _site 目录

      - name: Ensure deploy directory exists on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/chirpy-site/_site
            chown -R $USER:$USER /home/ubuntu/chirpy-site
        # 在上传 _site 之前，加一个步骤来远程创建目录并设置权限

      - name: Upload _site to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "_site/index.html"
          target: "/home/ubuntu/chirpy-site/_site"
        # 直接上传 _site 内容到服务器指定目录

      - name: Upload docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/chirpy-site/"

      - name: Upload nginx.conf
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "nginx.conf"
          target: "/home/ubuntu/chirpy-site/"

      - name: Start or Restart blog container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/chirpy-site
            docker compose down
            docker compose up -d
        # SSH 登录服务器，重启 nginx 容器，应用最新的 _site 内容
