name: Build and Deploy Chirpy Blog

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build static site with Jekyll
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Package _site directory
        run: tar czf site.tar.gz -C _site .

      - name: Upload site and config files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            site.tar.gz
            Dockerfile
            docker-compose.yml
            Gemfile
            Gemfile.lock
          target: /home/ubuntu/chirpy-site

      - name: Remote extract and restart Docker service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/chirpy-site
            tar xzf site.tar.gz
            rm site.tar.gz
            docker compose down
            docker compose up --build -d
