name: Build and Deploy Chirpy Blog

on:
  push:
    branches:
      - main # 监听 main 分支提交

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Chirpy static site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp -r _site/* deploy/

      - name: Upload static files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy/*"
          target: "/home/ubuntu/chirpy-site/_site"

      - name: Restart nginx container on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/chirpy-site
            docker compose restart blog
